Update integration-test.yml

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -118,7 +118,7 @@ jobs:
         with:
           python-version: "3.10"
 
-      - uses: actions/setup-node@v2
+      - uses: actions/setup-node@v4
         with:
           node-version: "20"
 
@@ -133,7 +133,7 @@ jobs:
           go-version: "1.21"
 
       - name: Start 4 node docker cluster
-        run: make clean && INVARIANT_CHECK_INTERVAL=10 ${{ matrix.test.env }} make docker-cluster-start &
+        run: make clean && INVARIANT_CHECK_INTERVAL=10 make docker-cluster-start
 
       - name: Wait for docker cluster to start
         run: |
@@ -141,7 +141,7 @@ jobs:
           sleep 10
 
       - name: Start rpc node
-        run: make run-rpc-node-skipbuild &
+        run: make run-rpc-node-skipbuild
 
       - name: Verify Sei Chain is running
         run: python3 integration_test/scripts/runner.py integration_test/startup/startup_test.yaml
@@ -149,7 +149,7 @@ jobs:
       - name: Run ${{ matrix.test.name }}
         run: |
           IFS=$'\n'
-          for script in $(echo '${{ toJson(matrix.test.scripts) }}' | jq -r '.[]'); do
+          for script in $(echo "${{ toJson(matrix.test.scripts) }}" | jq -r '.[]'); do
             bash -c "$script"
           done
           unset IFS
@@ -182,22 +182,15 @@ jobs:
     if: always()
     steps:
       - name: Get workflow conclusion
-        id: workflow_conclusion
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 2
-          retry_on: error
-          timeout_seconds: 30
-          command: |
-            jobs=$(curl -s https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
-            job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
-
-            for status in $job_statuses; do
-              echo "Status: $status"
-              if [[ "$status" == "failure" ]]; then
-                echo "Some or all tests have failed!"
-                exit 1
-              fi
-            done
-
-            echo "All tests have passed!"
+        run: |
+          jobs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
+          job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
+          for status in $job_statuses; do
+            echo "Status: $status"
+            if [[ "$status" == "failure" ]]; then
+              echo "❌ Some or all tests have failed!"
+              exit 1
+            fi
+          done
+          echo "✅ All tests have passed!"
