Unify code coverage configuration (#2441)
To avoid false negative code coverage target failure, unify the codecov
configuration.

Use flags to differentiate between different module coverage report and
set per module target.

diff --git a/.github/workflows/sei-cosmos-unit-test.yml b/.github/workflows/sei-cosmos-unit-test.yml
--- a/.github/workflows/sei-cosmos-unit-test.yml
+++ b/.github/workflows/sei-cosmos-unit-test.yml
@@ -27,50 +27,52 @@ jobs:
         with:
           go-version: 1.24
       - name: Create a file with all core Cosmos SDK pkgs
+        working-directory: ./sei-cosmos
         run: go list ./... > pkgs.txt
       - name: Split pkgs into 10 files
+        working-directory: ./sei-cosmos
         run: split -d -n l/10 pkgs.txt pkgs.txt.part.
       # cache multiple
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-00"
-          path: ./pkgs.txt.part.00
+          path: ./sei-cosmos/pkgs.txt.part.00
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-01"
-          path: ./pkgs.txt.part.01
+          path: ./sei-cosmos/pkgs.txt.part.01
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-02"
-          path: ./pkgs.txt.part.02
+          path: ./sei-cosmos/pkgs.txt.part.02
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-03"
-          path: ./pkgs.txt.part.03
+          path: ./sei-cosmos/pkgs.txt.part.03
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-04"
-          path: ./pkgs.txt.part.04
+          path: ./sei-cosmos/pkgs.txt.part.04
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-05"
-          path: ./pkgs.txt.part.05
+          path: ./sei-cosmos/pkgs.txt.part.05
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-06"
-          path: ./pkgs.txt.part.06
+          path: ./sei-cosmos/pkgs.txt.part.06
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-07"
-          path: ./pkgs.txt.part.07
+          path: ./sei-cosmos/pkgs.txt.part.07
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-08"
-          path: ./pkgs.txt.part.08
+          path: ./sei-cosmos/pkgs.txt.part.08
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-09"
-          path: ./pkgs.txt.part.09
+          path: ./sei-cosmos/pkgs.txt.part.09
 
   tests:
     runs-on: ubuntu-latest
@@ -78,7 +80,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        part: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09"]
+        part: [ "00", "01", "02", "03", "04", "05", "06", "07", "08", "09" ]
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v3
@@ -94,6 +96,7 @@ jobs:
       - uses: actions/download-artifact@v4
         with:
           name: "${{ github.sha }}-${{ matrix.part }}"
+          path: ./sei-cosmos
       - name: Get data from Go build cache
         uses: actions/cache@v3
         with:
@@ -104,13 +107,14 @@ jobs:
           key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
 
       - name: test & coverage report creation
+        working-directory: ./sei-cosmos
         run: |
           cat pkgs.txt.part.${{ matrix.part }} | xargs go test -mod=readonly -race -timeout 5m -coverprofile=${{ matrix.part }}profile.out -covermode=atomic -tags='ledger test_ledger_mock'
 
       - uses: actions/upload-artifact@v4
         with:
           name: "${{ github.sha }}-${{ matrix.part }}-coverage"
-          path: ./${{ matrix.part }}profile.out
+          path: ./sei-cosmos/${{ matrix.part }}profile.out
 
   upload-coverage-report:
     needs: tests
@@ -124,6 +128,8 @@ jobs:
       # Download all coverage reports from the 'tests' job
       - name: Download coverage reports
         uses: actions/download-artifact@v4
+        with:
+          path: ./sei-cosmos
 
       - name: Set GOPATH
         run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
@@ -135,23 +141,29 @@ jobs:
         run: go get github.com/wadey/gocovmerge && go install github.com/wadey/gocovmerge
 
       - name: Merge coverage reports
+        working-directory: ./sei-cosmos
         run: gocovmerge $(find . -type f -name '*profile.out') > coverage.txt
 
       - name: Check coverage report lines
+        working-directory: ./sei-cosmos
         run: wc -l coverage.txt
         continue-on-error: true
 
       - name: Check coverage report files
+        working-directory: ./sei-cosmos
         run: ls **/*profile.out
         continue-on-error: true
 
       # Now we upload the merged report to Codecov
       - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v4
+        uses: codecov/codecov-action@v5
         with:
-          file: ./coverage.txt
+          files: ./sei-cosmos/coverage.txt
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: true
+          flags: sei-cosmos
+          disable_search: true
+          name: sei-cosmos-coverage
 
   unit-test-check:
     name: Unit Test Check
@@ -167,16 +179,16 @@ jobs:
           retry_on: error
           timeout_seconds: 30
           command: |
-              jobs=$(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
-              job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
-
-              for status in $job_statuses
-              do
-                echo "Status: $status"
-                if [[ "$status" == "failure" ]]; then
-                  echo "Some or all tests have failed!"
-                  exit 1
-                fi
-              done
-
-              echo "All tests have passed!"
+            jobs=$(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
+            job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
+            
+            for status in $job_statuses
+            do
+              echo "Status: $status"
+              if [[ "$status" == "failure" ]]; then
+                echo "Some or all tests have failed!"
+                exit 1
+              fi
+            done
+            
+            echo "All tests have passed!"
